In [1]:
import pandas as pd

In [2]:
fpath = "/scratch/indikar_root/indikar1/shared_data/library_2_tsb/feature_barcodes/fbc_map.csv"

df = pd.read_csv(fpath)
print(f"{df.shape=}")
df['pred_split'] = df['pred'].apply(lambda x: "-".join(x.split("_")[2:]))
df.head()

df.shape=(652614, 32)

,cell_barcode,pred,chunk_1_PRRX1,chunk_1_PRRX1_MYOD,chunk_1_MYOD,chunk_2_PRRX1,chunk_2_PRRX1_MYOD,chunk_2_MYOD,chunk_3_PRRX1,chunk_3_PRRX1_MYOD,...,chunk_8_PRRX1,chunk_8_PRRX1_MYOD,chunk_8_MYOD,chunk_9_PRRX1,chunk_9_PRRX1_MYOD,chunk_9_MYOD,chunk_10_PRRX1,chunk_10_PRRX1_MYOD,chunk_10_MYOD,pred_split
0,AAACCATTCACGTAAT,chunk_1_PRRX1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRRX1
1,AAACCCGCATCCAATT,chunk_1_PRRX1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRRX1
2,AAACCCTGTAACGACA,chunk_1_PRRX1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRRX1
3,AAACGAATCCAGCACG,chunk_1_PRRX1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRRX1
4,AAACGAATCCCGCTTA,chunk_1_PRRX1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRRX1

In [3]:
df['pred_split'].value_counts()

pred_split
PRRX1-MYOD    358774
PRRX1         197669
MYOD           96171
Name: count, dtype: int64

In [4]:
df['pred_split'].value_counts(normalize=True)

pred_split
PRRX1-MYOD    0.549749
PRRX1         0.302888
MYOD          0.147363
Name: proportion, dtype: float64

In [5]:
gx = df.groupby('cell_barcode')['pred_split'].value_counts().reset_index()
gx = pd.pivot_table(gx, index='cell_barcode', columns='pred_split', values='count', aggfunc='sum')
print(f"{gx.shape=}")
gx['pred'] = gx.idxmax(axis=1)
gx.head()

gx.shape=(10831, 3)

pred_split        MYOD  PRRX1  PRRX1-MYOD        pred
cell_barcode
AAACCAAAGCAACTGC   1.0    2.0        22.0  PRRX1-MYOD
AAACCAAAGCTATGAT   1.0    2.0         4.0  PRRX1-MYOD
AAACCAAAGTAGCCGT   3.0    8.0        16.0  PRRX1-MYOD
AAACCAAAGTAGGGCA   3.0    1.0         1.0        MYOD
AAACCAAAGTCTAGGC   3.0    7.0        84.0  PRRX1-MYOD

In [12]:
(gx[['MYOD', 'PRRX1', 'PRRX1-MYOD']].std(axis=1) < 10).sum()

5005

In [6]:
gx['pred'].value_counts()

pred
PRRX1-MYOD    7838
PRRX1         2243
MYOD           750
Name: count, dtype: int64

In [7]:
gx['pred'].value_counts(normalize=True)

pred
PRRX1-MYOD    0.723664
PRRX1         0.207091
MYOD          0.069246
Name: proportion, dtype: float64

In [13]:
(21 * 1e9) / 225

93333333.33333333

In [14]:
(100 * 1e6) / 10000

10000.0